options:
  global-randoms:
    前缀词:
      type: strings
      value:
        - '45->|{Example1}'
        - '35->|{Example2}'
        - '10->|{Example3}'
        - '6->|{Example4}'
        - '3->|{Example5}'
        - '1->|{Example6}'
      strings:
        Example1:
          - '&8粗糙的'
          - '&e品质: &8粗糙'
          - '&f_______&b<-&8品质属性&b->>&f_______'
          - ' &d攻击力: &810 '
        Example2:
          - '&7普通的'
          - '&e品质: &7普通'
          - '&f_______&b<-&7品质属性&b->>&f_______'
          - ' &d攻击力: &720 '
        Example3:
          - '&3良好的'
          - '&e品质: &e良好'
          - '&f_______&b<-&e品质属性&b->>&f_______'
          - ' &d攻击力: &330 '
        Example4:
          - '&a优秀的'
          - '&e品质: &a优秀'
          - '&f_______&b<-&a品质属性&b->>&f_______'
          - ' &d攻击力: &a50 '
        Example5:
          - '&5史诗的'
          - '&e品质: &5史诗'
          - '&f_______&b<-&5品质属性&b->>&f_______'
          - ' &d攻击力: &570 '
        Example6:
          - '&6传说的'
          - '&e品质: &6传说'
          - '&f_______&b<-&6品质属性&b->>&f_______'
          - ' &d攻击力: &6100 '
    强度:
      type: number
      start: '1'
      bound: '20'