name: RandomItem
version: ${project.version}
main: com.skillw.randomitem.Main
api-version: 1.16
depend: [ PlaceholderAPI , NBTAPI ]
authors: [ Glom_ ]
commands:
  randomitem:
    aliases:
      - ri
    description: basic commannd.
