name: ${name}
main: ${main}
version: ${version}
softdepend: [ PlaceholderAPI , MythicMobs ]
author: Glom_
commands:
  randomitem:
    aliases:
      - ri
    description: basic commannd.

lib-download: true
lib-version: ${libVersion}
loader-version: ${loaderVersion}